### ISSUE TITLE
Hot reloading not working

### ISSUE THREAD

**Issue by timmeade** [center-key/node-slate#7]
Just forked the latest and hot reloading is not working.

I tried live-reload extension in chrome and no luck.   

Am I missing something?  It's been a while since i used gulp.   I remember using this a few years ago and it worked well.   

Now not so much. 

Thanks.

**Comment by pilafmon** [comment]
I'm not using any Chrome extensions, but the automatic rebuild is working for me.

After making an edit to `source/includes/main.md` and saving the change:
![node-slate-rebuild](https://user-images.githubusercontent.com/119555/52169415-cde53a00-26ec-11e9-843a-15db99458099.png)

@TimMeade Can you add the specific steps required to reproduce the issue you encountered?
